<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            'supplier_id' => '1',
            'category_id' => '5',
            'code' => 210383,
            'name' =>'Presente natura essencial oud feminino',
            'description' => '1 Deo parfum feminino 100 ml 1 Óleo desodorante corporal perfumado feminino 150 ml exclusivo 1 Caixa especial de natal com cinta',
            'departament' => 'Presente natura essencial oud feminino',
            'purchase_price' => 282.94,
            'resale_price' => 404.20,
            'percentage' => 30,
            'photo_url' =>'210383_1766539496.jpg',
            'non_production' => 0,
            'confirmed' => 0,
            'created_at' => now(),
            'updated_at' => now(),
            ]);
                
        DB::table('products')->insert([

            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210200,
            `name` => 'Presente natura essencial oud masculino', 
            `description` => '1 Deo parfum masculino 100 ml 1 Desodorante hidratante corporal perfumado masculino 100 ml exclusivo 1 Shower gel perfumado masculino 4 em 1: cabelo, corpo, barba e rosto 100 g exclusivo 1 Caixa especial de natal com cinta', 
            `departament` => 'Presente natura essencial oud masculino', 
            `purchase_price` => 252.91, 
            `resale_price` => 361.30, 
            `percentage` => '30', 
            `photo_url` => '210200_1766540867.jpg',   
            `points` => 21, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
        
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210357,
            `name` => 'Presente natura homem cor.agio', 
            `description` => '1 Deo parfum masculino 100 ml 1 Balm pós-barba perfumado 75 ml exclusivo 1 Creme para barbear perfumado 75 ml exclusivo 1 Caixa especial de natal com cinta', 
            `departament` => 'Presente natura homem cor.agio', 
            `purchase_price` => 300.09, 
            `resale_price` => 428.70, 
            `percentage` => '30', 
            `photo_url` => '210357_1766541266.jpg',  
            `points` => 27, 
            'created_at' => now(),
                    'updated_at' => now(),
                ]);
                
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210439,
            `name` => 'Presente natura una celebrar com batom', 
            `description` => '1 Deo parfum feminino 75 ml novo 1 Batom CC hidratante FPS 25 3,8 g (cor a escolher ao lado) novo 1 Caixa especial de presente P', 
            `departament` => 'Presente natura una celebrar com batom', 
            `purchase_price` => 267.33, 
            `resale_price` => 381.90, 
            `percentage` => '30', 
            `photo_url` => '210439jpg_1766541796.jpg',  
            `points` => 34, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
        
        DB::table('products')->insert([	 
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 219398,
            `name` => 'Presente natura tododia cereja e avelã', 
            `description` => '1 Creme desodorante nutritivo para o corpo 400 ml exclusivo 1 Caixa de sabonetes em barra puro vegetal 5 unidades de 90 g cada exclusiva 1 Envelope de presente', 
            `departament` => 'Presente natura tododia cereja e avelã', 
            `purchase_price` => 75.76, 
            `resale_price` => 109.80, 
            `percentage` => '30', 
            `photo_url` => '219398_1766542173.jpg', 
            `points` => 7, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
        
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` =>  188809,
            `name` => 'Presente natura tododia framboesa e pimenta vermelha', 
            `description` => '1 Body splash desodorante colônia feminino 60 ml exclusivo 1 Creme desodorante nutritivo para o corpo 80 ml exclusivo 1 Sabonete líquido cremoso para', 
            `departament` => 'Presente natura tododia framboesa e pimenta vermelha', 
            `purchase_price` => 69.93, 
            `resale_price` => 99.90, 
            `percentage` => '30', 
            `photo_url` => '188809_1766542929.jpg', 
            
            'created_at' => now(),
            'updated_at' => now(),
            ]);
        
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` =>  189574,
            `name` => 'Presente natura ekos cremes para mãos', 
            `description` => '1 Trio mãos natura ekos (1 Creme hidratante para mãos castanha, 1 Creme hidratante para mãos cacau, 1 Creme hidr', 
            `departament` => 'Presente natura ekos cremes para mãos', 
            `purchase_price` => 83.93, 
            `resale_price` => 119.90, 
            `percentage` => '30', 
            `photo_url` => '189574_1766543230.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);

        DB::table('products')->insert([
            `supplier_id` => 1,
            `category_id' => 5,
            'code' => 210372, 
            'name' => 'Presente natura luna intensa',
            'description' => '1 Deo parfum feminino 50 ml 1 Desodorante hidratante corporal iluminador perfumado 200 g exclusivo 1 Sacola de presente P com laço', 
            'departament' => 'Presente natura luna intensa',
            'purchase_price' => 260.26,
            'resale_price' => 371.80, 
            'percentage' => '30',
            'photo_url` => '210372_1766543618.jpg', 
            `points` => 22,
            'created_at' => now(),
            'updated_at' => now(),
            ]);
        
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210290,
            `name` => 'Presente natura kaiak oceano feminino', 
            `description` => '1 Desodorante colônia feminino 100 ml 1 Desodorante colônia feminino 25 ml exclusivo 1 Caixa de sabonetes em barra femininos 2 unidades de 90 g cada exclusiva 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura kaiak oceano feminino', 
            `purchase_price` => 197.82, 
            `resale_price` => 282.60, 
            `percentage` => '30', 
            `photo_url` => '210290_1766544089.jpg',  
            `points` => 15, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
        
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210289,
            `name` => 'Presente natura kaiak urbe', 
            `description` => '1 Desodorante colônia masculino 100 ml 1 Gel para barbear perfumado 75 g exclusivo 1 Gel pós-barba perfumado 75 g exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura kaiak urbe', 
            `purchase_price` => 220.29, 
            `resale_price` => 314.70, 
            `percentage` => '30', 
            `photo_url` => '210289_1766584965.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210362,
            `name` => 'Presente natura ilía', 
            `description` => '1 Deo parfum feminino 50 ml 1 Desodorante corporal 100 ml exclusivo 1 Desodorante hidratante corporal perfumado 80 ml exclusivo 1 Caixa especial de natal', 
            `departament` => 'Presente natura ilía', 
            `purchase_price` => 211.19, 
            `resale_price` => 301.70, 
            `percentage` => '30', 
            `photo_url` => '210362_1766585416.jpg',  
            `points` => 20, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1,
            `category_id` => 5, 
            `code` => 210393,
            `name` => 'Presente natura ekos castanha completo', 
            `description` => '1 Creme desodorante hidratante para o corpo 400 ml 1 Creme hidratante para os pés 40 g exclusivo 1 Creme hidratante para as mãos 75 g 1 Caixa de sabonetes em barra puro vegetal 2 unidades de 100 g cada exclusiva 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura ekos castanha completo', 
            `purchase_price` => 149.52, 
            `resale_price` => 213.60, 
            `percentage` => '30', 
            `photo_url` => '210393_1766585869.jpg',  
            `points` => 13, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 205404,
            `name` => 'Presente natura luna girl', 
            `description` => '1 Desodorante colônia feminino 25 ml exclusivo 1 Gel desodorante hidratante iluminador corporal 100 g exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura luna girl', 
            `purchase_price` => 92.47, 
            `resale_price` => 132.10, 
            `percentage` => '30', 
            `photo_url` => '205404_1766586319.jpg',  
            `points` => 9, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210387,
            `name` => 'Presente natura kriska', 
            `description` => '1 Desodorante colônia feminino 100 ml 1 Mousse desodorante hidratante corporal feminina 200 g exclusiva 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura kriska',
            `purchase_price` =>  173.45, 
            `resale_price` => 247.79, 
            `percentage` => '30', 
            `photo_url` => '210387_1766586591.jpg',  
            `points` => 15, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 218540,
            `name` => 'Presente natura mamãe e bebê miniaturas', 
            `description` => '1 Água de colônia 50 ml exclusiva 1 Hidratante 50 ml exclusivo 1 Sabonete líquido 50 ml exclusivo 1 Caixa personalizada', 
            `departament` => 'Presente natura mamãe e bebê miniaturas', 
            `purchase_price` => 111.30, 
            `resale_price` => 159.00, 
            `percentage` => '30', 
            `photo_url` => '218540_1766586880.jpg',   
            `points` => 9, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1,
            `category_id` => 5, 
            `code` =>  186441,
            `name` => 'Presente natura tododia sabonetes', 
            `description` => '1 Caixa de sabonetes em barra puro vegetal sortidos 5 unidades (2 ameixa e flor de baunilha, 2 frutas vermelhas e 1 amora vermelha e jabuticaba) de 90 g cada exclusiva', 
            `departament` => 'Presente natura tododia sabonetes', 
            `purchase_price` => 27.93, 
            `resale_price` => 39.90, 
            `percentage` => '30', 
            `photo_url` => '186441_1766587516.jpg',  
            `points` => 3, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210419,
            `name` => 'Presente natura tododia romã e amêndoas glaceadas', 
            `description` => '1 Body splash desodorante colônia feminino 200 ml exclusivo 1 Creme desodorante nutritivo para o corpo 400 ml exclusivo 1 Caixa de sabonetes em barra puro vegetal 5 unidades de 90 g cada exclusiva 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura tododia romã e amêndoas glaceadas', 
            `purchase_price` => 138.39, 
            `resale_price` => 197.70, 
            `percentage` => '30', 
            `photo_url` => '210419_1766590708.jpg',   
            `points` => 13, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210204,
            `name` => 'Presente natura essencial exclusivo masculino', 
            `description` => '1 Deo parfum masculino 100 ml 1 Creme de barbear 75 g exclusivo 1 Balm pós-barba 75 ml exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura essencial exclusivo masculino', 
            `purchase_price` => 297.28, 
            `resale_price` => 424.69, 
            `percentage` => '30', 
            `photo_url` => '210204_1766591033.jpg',   
            `points` => 22, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, `code` => 210198,
            `name` => 'Presente natura essencial exclusivo feminino completo', `
            description` => '1 Deo parfum feminino 100 ml 1 Desodorante corporal feminino 100 ml exclusivo 1 Desodorante hidratante iluminador corporal perfumado feminino 100 ml exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura essencial exclusivo feminino completo', 
            `purchase_price` => 306.39, 
            `resale_price` => 437.70, 
            `percentage` => '30', 
            `photo_url` => '210198_1766591615.jpg',  
            `points` => 40, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, `code` => 210376,
            `name` => 'Presente natura luna rosé', 
            `description` => '1 Desodorante colônia feminino 75 ml exclusivo 1 Desodorante hidratante corporal perfumado 300 ml exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura luna rosé', 
            `purchase_price` => 193.06, 
            `resale_price` => 275.80, 
            `percentage` => '30', 
            `photo_url` => '210376_1766591979.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210416,
            `name` => 'Presente natura tododia macadâmia', 
            `description` => '1 Body splash desodorante colônia feminino 200 ml 1 Creme desodorante nutritivo para o corpo 400 ml 1 Espuma cremosa de banho 150 ml exclusiva 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura tododia macadâmia', 
            `purchase_price` => 173.95, 
            `resale_price` => 248.50, 
            `percentage` => '30', 
            `photo_url` => '210416_1766600121.jpg',  
            `points` => 14, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210414,
            `name` => 'Presente natura tododia pêssego e flor de cravo', 
            `description` => '1 Sabonete líquido em gel para o corpo 100 g exclusivo 1 Creme nutritivo para mãos 50 ml exclusivo 1 Creme desodorante nutritivo para o corpo 100 ml exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura tododia pêssego e flor de cravo', 
            `purchase_price` => 59.29, 
            `resale_price` => 84.70, 
            `percentage` => '30', 
            `photo_url` => '210414_1766600427.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210280,
            `name` => 'Presente natura humor liberta', 
            `description` => '1 Desodorante colônia 75 ml 1 Gel desodorante hidratante iluminador corporal perfumado 200 g exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura humor liberta', 
            `purchase_price` => 172.83, 
            `resale_price` => 246.90, 
            `percentage` => '30', 
            `photo_url` => '210280_1766600712.jpg', 
            `points` => 14, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210288,
            `name` => 'Presente natura kaiak aventura feminino', 
            `description` => '1 Desodorante colônia feminino 100 ml 1 Creme desodorante hidratante refrescante 2 em 1 banho e pós-banho feminino 390 ml exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura kaiak aventura feminino', 
            `purchase_price` => 200.76, 
            `resale_price` => 286.80, 
            `percentage` => '30', 
            `photo_url` => '210288_1766601046.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210285,
            `name` => 'Presente natura kaiak aventura masculino', 
            `description` => '1 Desodorante colônia masculino 100 ml 1 Desodorante corporal masculino 100 ml exclusivo 1 Sabonete em barra puro vegetal masculino 90 g exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura kaiak aventura masculino', 
            `purchase_price` => 179.90, 
            `resale_price` => 257.00, 
            `percentage` => '30', 
            `photo_url` => '210285_1766601297.jpg',  
            `points` => 14, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210203,
            `name` => 'Presente natura humor a rigor',
            `description` => '1 Desodorante colônia masculino 75 ml exclusivo 1 Desodorante colônia masculino 25 ml exclusivo 1 Desodorante hidratante corporal perfumado 100 ml exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura humor a rigor', 
            `purchase_price` => 182.07, 
            `resale_price` => 260.10, 
            `percentage` => '30', 
            `photo_url` => '210203_1766601527.jpg',  
            `points` => 15, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210279,
            `name` => 'Presente natura humor próprio', 
            `description` => '1 Desodorante colônia feminino 75 ml 1 Body splash desodorante colônia feminino 200 ml exclusivo 1 Calda desodorante hidratante corporal feminina 120 ml exclusiva 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura humor próprio', 
            `purchase_price` => 223.09, 
            `resale_price` => 318.70, 
            `percentage` => '30', 
            `photo_url` => '210279_1766601770.jpg',  
            `points` => 19, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210292,
            `name` => 'Presente natura mamãe e bebê flor de laranjeira', 
            `description` => '1 Água de colônia 100 ml exclusiva 1 Hidratante 100 ml exclusivo 1 Sabonete líquido 100 ml exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura mamãe e bebê flor de laranjeira', 
            `purchase_price` => 116.55, 
            `resale_price` => 166.50, 
            `percentage` => '30', 
            `photo_url` => '210292_1766604455.jpg',  
            `points` => 9, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210572,
            `name` => 'Presente natura tododia cabelos hidratação', 
            `description` => '1 Spray hidratante maçã verde e aloe vera 200 ml 1 Shampoo hidratante maçã verde e aloe vera 300 ml 1 Condicionador hidratante maçã verde e aloe vera 280 ml 1 Envelope de presente', 
            `departament` => 'Presente natura tododia cabelos hidratação', 
            `purchase_price` => 75.39, 
            `resale_price` => 107.70, 
            `percentage` => '30', 
            `photo_url` => '210572_1766604686.jpg',  
            `points` => 8, 
        'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 213311,
            `name` => 'Presente natura crer para ver pocket bag', 
            `description` => '1 Bolsa crossbody C 20 x L 6,5 x A 13 cm lançamento', 
            `departament` => 'Presente natura crer para ver pocket bag', 
            `purchase_price` => 62.93,
            `resale_price` => 89.90, 
            `percentage` => '30', 
            `photo_url` => '213311_1766605014.jpg',  
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 216573,
            `name` => 'Presente natura crer para ver nécessaire organizador', 
            `description` => '1 Nécessaire organizador de viagem C 25 x L 10 x A 18 cm lançamento', 
            `departament` => 'Presente natura crer para ver nécessaire organizador', 
            `purchase_price` => 34.93, 
            `resale_price` => 49.90, 
            `percentage` => '30', 
            `photo_url` => '216573_1766605244.jpg',  
            `points` => 6, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210385,
            `name` => 'Presente natura ekos madeira em flor', 
            `description` => '1 Desodorante colônia frescor feminino 150 ml exclusivo 1 Creme desodorante hidratante para o corpo 250 ml exclusivo 1 Creme hidratante para mãos 40 g exclusivo 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura ekos madeira em flor', 
            `purchase_price` => 162.89, 
            `resale_price` => 232.70, 
            `percentage` => '30', 
            `photo_url` => '210385_1766605584.jpg',  
            `points` => 14, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);

        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210370,
            `name` => 'Presente natura ekos castanha', 
            `description` => '1 Creme desodoranre hidratante para o corpo 200 ml 1 Sabonete em barra puro vegetal 100 g exclusivo 1 Envelope de presente', 
            `departament` => 'Presente natura ekos castanha', 
            `purchase_price` => 51.03, 
            `resale_price` => 72.90, 
            `percentage` => '30', 
            `photo_url` => '210370_1766605871.jpg',  
            `points` => 6, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 216572,
            `name` => 'Presente natura trio de desodorantes feminino', 
            `description` => '1 Desodorante corporal luna absoluta feminino 100 ml exclusivo 1 Desodorante corporal kriska shock feminino 100 ml exclusivo 1 Desodorante corporal kaiak oceano feminino 100 ml 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura trio de desodorantes feminino', 
            `purchase_price` => 115.29, 
            `resale_price` => 164.70, 
            `percentage` => '30', 
            `photo_url` => '216572_1766606124.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 210354,
            `name` => 'Presente natura naturé', 
            `description` => '1 Colônia corre corre 100 ml exclusiva 1 Caixa de sabonetes em barra 2 unidades de 90 g cada exclusiva 1 Sacola de presente P com laço', 
            `departament` => 'Presente natura naturé', 
            `purchase_price` => 99.11, 
            `resale_price` => 141.59, 
            `percentage` => '30', 
            `photo_url` => '210354_1766606359.jpg',  
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 5, 
            `code` => 2104391,
            `name` => 'paramela com um brilho radiante de pimenta-rosa e mandarina', 
            `description` => '1 Deo parfum feminino 75 ml novo 1 Sacola de presente P com laço', 
            `departament` => 'paramela com um brilho radiante de pimenta-rosa e mandarina', 
            `purchase_price` => 223.30, 
            `resale_price` => 319.00, 
            `percentage` => '30', 
            `photo_url` => '210439-1_1766607013.jpg',  
            `points` => 29, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 119046,
            `name` => 'Fragrância adocicada que conecta madeiras quentes', 
            `description` => 'Natura una somos deo parfum', 
            `departament` => 'Fragrância adocicada que conecta madeiras quentes à beleza de notas florais da davana e do jasmim', 
            `purchase_price` => 223.30, 
            `resale_price` => 319.00, 
            `percentage` => '30', 
            `photo_url` => '119046_1766613376.jpg',   
            `points` => 29, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 2446,
            `name` => 'Natura una deo parfum feminino',  
            `description` => 'Natura una deo parfum feminino 75 ml  Adocicado intenso.', 
            `departament` => 'Natura una deo parfum feminino 75 ml', 
            `purchase_price` => 223.29, 
            `resale_price` => 318.98, 
            `percentage` => '30', 
            `photo_url` => '2446_1766613636.jpg',  
            `points` => 29, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 128756,
            `name` => 'Natura una blush deo parfum feminino', 
            `description` => 'Natura una blush deo parfum feminino 75 ml • Adocicado intenso.', 
            `departament` => 'Natura una blush deo parfum feminino 75 ml', 
            `purchase_price` => 223.30, 
            `resale_price` => 319.00, 
            `percentage` => '30', 
            `photo_url` => '128756_1766613857.jpg',  
            `points` => 29, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);

        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 2458,
            `name` => 'Natura una artisan deo parfum feminino', 
            `description` => 'Natura una artisan deo parfum feminino1 75 ml  Chipre intenso.', 
            `departament` => 'Natura una artisan deo parfum feminino1 75 ml', 
            `purchase_price` => 223.30, 
            `resale_price` => 319.00, 
            `percentage` => '30', 
            `photo_url` => '2458_1766614063.jpg',  
            `points` => 29, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 140595,
            `name` => 'Desodorante hidratante corporal perfumado una artisan', 
            `description` => 'Desodorante hidratante corporal perfumado una artisan 200 g • Embalagem de vidro', 
            `departament` => 'Desodorante hidratante corporal perfumado una artisan 200 g', 
            `purchase_price` => 90.92, 
            `resale_price` => 129.89, 
            `percentage` => '30', 
            `photo_url` => '140595_1766614380.jpg',   
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 105359,
            `name` => 'Amadeirado especiado.', 
            `description` => 'Amadeirado especiado. A combinação do palo santo com o cumaru dá origem a uma fragrância intensa, exuberante e sofisticada. Deo parfum essencial palo santo', 
            `departament` => 'Amadeirado especiado', 
            `purchase_price` => 195.22, 
            `resale_price` => 278.89, 
            `percentage` => '30', 
            `photo_url` => '105359_1766614683.jpg',  
            `points` => 25, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 27264,
            `name` => 'Deo parfum essencial mirra feminino', 
            `description` => 'Amadeirado adocicado. Um encontro magnífico de mirras que dá vida a uma fragrância inesquecível de intensa personal', 
            `departament` => 'Deo parfum essencial mirra feminino 100 ml', 
            `purchase_price` => 195.23, 
            `resale_price` => 278.90, 
            `percentage` => '30', 
            `photo_url` => '27264_1766615585.jpg',  
            `points` => 25, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, `code` => 194226,
            `name` => 'Deo parfum essencial desejos feminino', 
            `description` => 'Deo parfum essencial desejos feminino 100 ml', 
            `departament` => 'Deo parfum essencial desejos feminino 100 ml', 
            `purchase_price` => 186.83, 
            `resale_price` => 266.90, 
            `percentage` => '30', 
            `photo_url` => '194226_1766616004.jpg',  
            `points` => 26, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, `code` => 114583,
            `name` => 'Deo parfum essencial ato feminino', 
            `description` => 'Deo parfum essencial ato feminino2 100 ml', 
            `departament` => 'Deo parfum essencial ato feminino2 100 ml', 
            `purchase_price` => 195.23, 
            `resale_price` => 278.90, 
            `percentage` => '30', 
            `photo_url` => '114583_1766616236.jpg',  
            `points` => 25, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, `code` => 167756,
            `name` => 'Deo parfum essencial sentir feminino', 
            `description` => 'Deo parfum essencial sentir feminino 100 ml', 
            `departament` => 'Deo parfum essencial sentir feminino 100 ml', 
            `purchase_price` => 198.02, 
            `resale_price` => 278.90, 
            `percentage` => '30', 
            `photo_url` => '167756_1766616457.jpg',  
            `points` => 25, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 165813,
            `name` => 'Deo parfum essencial atrai feminino 100 ml', 
            `description` => 'Deo parfum essencial atrai feminino 100 ml', 'Deo parfum essencial atrai feminino 100 ml', 
            `purchase_price` => 198.02, 
            `resale_price` => 278.90, 
            `percentage` => '30', 
            `photo_url` => '165813_1766616769.jpg',  
            `points` => 25, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 107121,
            `name` => 'Deo parfum essencial único feminino 90 ml', 
            `description` => 'Deo parfum essencial único feminino 90 ml', 
            `departament` => 'Deo parfum essencial único feminino 90 ml', 
            `purchase_price` => 224.63, 
            `resale_price` => 320.90, 
            `percentage` => '30', 
            `photo_url` => '107121_1766617511.jpg',  
            `points` => 29, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 76423,
            `name` => 'Deo parfum essencial exclusivo feminino 100 ml', 
            `description` => 'Deo parfum essencial exclusivo feminino 100 ml', 
            `departament` => 'Deo parfum essencial exclusivo feminino 100 ml', 
            `purchase_price` => 195.23, 
            `resale_price` => 278.90, 
            `percentage` => '30', 
            `photo_url` => '76423_1766617891.jpg',  
            `points` => 19, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 16871,
            `name` => 'Desodorante hidratante corporal perfumado essencial exclusivo', 
            `description` => 'Desodorante hidratante corporal perfumado essencial exclusivo 200 g', 
            `departament` => 'Desodorante hidratante corporal perfumado essencial exclusivo 200 g', 
            `purchase_price` => 90.93, 
            `resale_price` => 129.90, 
            `percentage` => '30', 
            `photo_url` => '16871_1766618383.jpg',  
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 76425,
            `name` => 'Deo parfum essencial oud feminino', 
            `description` => 'Deo parfum essencial oud feminino3 100 ml', 
            `departament` => 'Deo parfum essencial oud feminino3 100 ml', 
            `purchase_price` => 195.23, 
            `resale_price` => 278.90, 
            `percentage` => '30', 
            `photo_url` => '11682_1766672590.jpg',  
            `points` => 25, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 11682,
            `name` => 'Natura Refil Essencial Oud Deo Parfum Feminino', 
            `description` => 'Natura Refil Essencial Oud Deo Parfum Feminino 100 Ml', 
            `departament` => 'Natura Refil Essencial Oud Deo Parfum Feminino 100 Ml', 
            `purchase_price` => 149.73, 
            `resale_price` => 213.90, 
            `percentage` => '30', 
            `photo_url` => '76425_1766673678.jpg',  
            `points` => 19, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 16872,
            `name` => 'Desodorante hidratante corporal perfumado essencial oud 200 g', 
            `description` => 'Desodorante hidratante corporal perfumado essencial oud 200 g', 
            `departament` => 'Desodorante hidratante corporal perfumado essencial oud 200 g', 
            `purchase_price` => 90.93, 
            `resale_price` => 129.90, 
            `percentage` => '30', 
            `photo_url` => '16872_1766674019.jpg',  
            `points` => 10, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 98943,
            `name` => 'Refil Desodorante Hidratante Corporal Perfumado Essencial Oud', 
            `description` => 'Refil Desodorante Hidratante Corporal Perfumado Essencial Oud', 
            `departament` => 'Refil Desodorante Hidratante Corporal Perfumado Essencial Oud', 
            `purchase_price` => 67.13, 
            `resale_price` => 95.90, 
            `percentage` => '30', 
            `photo_url` => '98943_1766674436.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 76421,
            `name` => 'Deo parfum essencial feminino 100 ml', 
            `description` => 'Deo parfum essencial feminino 100 ml', 
            `departament` => 'Deo parfum essencial feminino 100 ml', 
            `purchase_price` => 195.22, 
            `resale_price` => 278.89, 
            `percentage` => '30', 
            `photo_url` => '76421_1766675019.jpg',  
            `points` => 25, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 16870,
            `name` => 'Desodorante hidratante corporal perfumado essencial 200 g', 
            `description` => 'Desodorante hidratante corporal perfumado essencial 200 g', 
            `departament` => 'Desodorante hidratante corporal perfumado essencial 200 g', 
            `purchase_price` => 90.93, 
            `resale_price` => 129.90, 
            `percentage` => '30', 
            `photo_url` => '16870_1766675366.jpg',  
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 7978,
            `name` => 'REFIL Deo parfum essencial feminino 100 ml', 
            'description' => 'REFIL Deo parfum essencial feminino 100 ml', 
            `departament` => 'REFIL Deo parfum essencial feminino 100 ml', 
            `purchase_price` => 149.73, 
            `resale_price` => 213.90, 
            `percentage` => '30', 
            `photo_url` => '7978_1766676113.jpg',  
            `points` => 19, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 98941,
            `name` => 'REFIL Desodorante hidratante corporal perfumado', 
            `description` => 'REFIL Desodorante hidratante corporal perfumado', 
            `departament` => 'REFIL Desodorante hidratante corporal perfumado', 
            `purchase_price` => 67.12, 
            `resale_price` => 95.89, 
            `percentage` => '30', 
            `photo_url` => '98941_1766676543.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 95563,
            `name` => 'Deo parfum essencial supreme feminino 100 ml', 
            `description` => 'Deo parfum essencial supreme feminino 100 ml', 
            `departament` => 'Deo parfum essencial supreme feminino 100 ml', 
            `purchase_price` => 195.23, 
            `resale_price` => 278.90, 
            `percentage` => '30', 
            `photo_url` => '95563_1766678506.jpg',  
            `points` => 25, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 16873,
            `name` => 'Desodorante hidratante corporal perfumado essencial supreme', 
            `description` => 'Desodorante hidratante corporal perfumado essencial supreme 200 g', 
            `departament` => 'Desodorante hidratante corporal perfumado essencial supreme 200 g', 
            `purchase_price` => 90.93, 
            `resale_price` => 129.90, 
            `percentage` => '30', 
            `photo_url` => '16873_1766678821.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 98944,
            `name` => 'REFIL Desodorante hidratante corporal perfumado', 
            `description` => 'REFIL Desodorante hidratante corporal perfumado essencial supreme 200 g', 
            `departament` => 'REFIL Desodorante hidratante corporal perfumado essencial supreme 200 g', 
            `purchase_price` => 67.13, 
            `resale_price` => 95.90, 
            `percentage` => '30', 
            `photo_url` => '98944_1766679235.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 171364,
            `name` => 'Desodorante colônia luna divina feminino', 
            `description` => 'Desodorante colônia luna divina feminino 75 ml', 
            `departament` => 'Desodorante colônia luna divina feminino 75 ml', 
            `purchase_price` => 127.33, 
            `resale_price` => 181.90, 
            `percentage` => '30', 
            `photo_url` => '171364_1766682848.jpg',  
            `points` => 15, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 173003,
            `name` => 'Desodorante hidratante iluminador corporal perfumado luna divina', 
            `description` => 'Desodorante hidratante iluminador corporal perfumado luna divina 150 ml', 
            `departament` => 'Desodorante hidratante iluminador corporal perfumado luna divina 150 ml', 
            `purchase_price` => 44.73, 
            `resale_price` => 63.90, 
            `percentage` => '30', 
            `photo_url` => '173003_1766683254.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 177162,
            `name` => 'Desodorante hidratante corporal perfumado luna liberdade', 
            `description` => 'Desodorante hidratante corporal perfumado luna liberdade1 300 ml', 
            `departament` => 'Desodorante hidratante corporal perfumado luna liberdade1 300 ml', 
            `purchase_price` => 65.73, 
            `resale_price` => 93.90, 
            `percentage` => '30', 
            `photo_url` => '177162_1766683757.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 169776,
            `name` => 'Desodorante colônia luna liberdade feminino', 
            `description` => 'O chipre Natura ganha facetas irresistíveis combinado com a maçã cristalizada, um buquê floral feminino e a cremosidade da baunilha.', 
            `departament` => 'Desodorante colônia luna liberdade feminino 75 ml', 
            `purchase_price` => 129.15, 
            `resale_price` => 181.90, 
            `percentage` => '30', 
            `photo_url` => '169776_1766684180.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 44452,
            `name` => 'Desodorante colônia luna feminino', 
            `description` => 'Desodorante colônia luna feminino 75 ml', 
            `departament` => 'Desodorante colônia luna feminino 75 ml', 
            `purchase_price` => 127.33, 
            `resale_price` => 181.90, 
            `percentage` => '30', 
            `photo_url` => '44452_1766684690.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 97168,
            `name` => 'Desodorante hidratante corporal perfumado luna', 
            `description` => 'Desodorante hidratante corporal perfumado luna1 300 ml', 
            `departament` => 'Desodorante hidratante corporal perfumado luna1 300 ml', 
            `purchase_price` => 46.15, 
            `resale_price` => 65.00, 
            `percentage` => '30', 
            `photo_url` => '97153_1766685079.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 150216,
            `name` => 'Perfume para cabelos luna', 
            `description` => 'Perfume para cabelos luna 30 ml', 
            `departament` => 'Perfume para cabelos luna 30 ml', 
            `purchase_price` => 54.53, 
            `resale_price` => 77.90, 
            `percentage` => '30', 
            `photo_url` => '150216_1766685439.jpg',  
            `points` => 6, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 2550,
            `name` => 'Desodorante colônia luna radiante feminino', 
            `description` => 'Desodorante colônia luna radiante feminino1 75 ml', 
            `departament` => 'Desodorante colônia luna radiante feminino1 75 ml', 
            `purchase_price` => 127.33, 
            `resale_price` => 181.90, 
            `percentage` => '30', 
            `photo_url` => '2550_1766685951.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 97170,
            `name` => 'REFIL Desodorante hidratante corporal perfumado luna radiante', 
            `description` => 'REFIL Desodorante hidratante corporal perfumado luna radiante2 300 ml', 
            `departament` => 'REFIL Desodorante hidratante corporal perfumado luna radiante2 300 ml', 
            `purchase_price` => 45.50, 
            `resale_price` => 65.00, 
            `percentage` => '30', 
            `photo_url` => '97170_1766749272.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 128615,
            `name` => 'Desodorante colônia luna ousadia feminino', 
            `description` => 'Desodorante colônia luna ousadia feminino3 75 ml', 
            `departament` => 'Desodorante colônia luna ousadia feminino3 75 ml', 
            `purchase_price` => 127.33, 
            `resale_price` => 181.90, 
            `percentage` => '30', 
            `photo_url` => '128615_1766749516.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 129620,
            `name` => 'Desodorante hidratante corporal perfumado luna ousadia', 
            `description` => 'Desodorante hidratante corporal perfumado luna ousadia4 300 ml', 
            `departament` => 'Desodorante hidratante corporal perfumado luna ousadia4 300 ml', 
            `purchase_price` => 65.73, 
            `resale_price` => 93.90, 
            `percentage` => '30', 
            `photo_url` => '129620_1766749679.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 129617,
            `name` => 'REFIL Desodorante hidratante corporal perfumado luna ousadia', 
            `description` => 'REFIL Desodorante hidratante corporal perfumado luna ousadia4 300 ml', 
            `departament` => 'REFIL Desodorante hidratante corporal perfumado luna ousadia4 300 ml', 
            `purchase_price` => 45.49, 
            `resale_price` => 64.98, 
            `percentage` => '30', 
            `photo_url` => '129617_1766749855.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` =>  56417,
            `name` => 'Desodorante colônia luna absoluta feminino', 
            `description` => 'Desodorante colônia luna absoluta feminino 75 ml', 
            `departament` => 'Desodorante colônia luna absoluta feminino 75 ml', 
            `purchase_price` => 127.33, 
            `resale_price` => 181.90, 
            `percentage` => '30', 
            `photo_url` => '56417_1766750025.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 97171,
            `name` => 'Desodorante hidratante corporal perfumado luna absoluta', 
            `description` => 'Desodorante hidratante corporal perfumado luna absoluta2 300 ml', 
            `departament` => 'Desodorante hidratante corporal perfumado luna absoluta2 300 ml', 
            `purchase_price` => 65.73, 
            `resale_price` => 93.90, 
            `percentage` => '30', 
            `photo_url` => '97171_1766750176.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 115659,
            `name` => 'REFIL Desodorante hidratante corporal perfumado luna absoluta', 
            `description` => 'REFIL Desodorante hidratante corporal perfumado luna absoluta2 300 ml', 
            `departament` => 'REFIL Desodorante hidratante corporal perfumado luna absoluta2 300 ml', 
            `purchase_price` => 45.50, 
            `resale_price` => 65.00, 
            `percentage` => '30', 
            `photo_url` => '115659_1766750363.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 102038,
            `name` => 'Desodorante colônia luna confiante feminino', 
            `description` => 'Desodorante colônia luna confiante feminino5 75 ml', 
            `departament` => 'Desodorante colônia luna confiante feminino5 75 ml', 
            `purchase_price` => 127.33, 
            `resale_price` => 181.90, 
            `percentage` => '30', 
            `photo_url` => '102038_1766750524.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 102039,
            `name` => 'Desodorante hidratante corporal perfumado luna confiante', 
            `description` => 'Desodorante hidratante corporal perfumado luna confiante2 300 ml', 
            `departament` => 'Desodorante hidratante corporal perfumado luna confiante2 300 ml', 
            `purchase_price` => 65.73, 
            `resale_price` => 93.90, 
            `percentage` => '30', 
            `photo_url` => '102039_1766750653.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 102420,
            `name` => 'REFIL  luna confiante feminino', 
            `description` => 'REFIL  luna confiante feminino5 75 ml • Chipre musk. Desodorante hidratante corporal perfumado luna confiante2 300 m', 
            `departament` => 'REFIL  luna confiante feminino5 75 ml • Desodorante hidratante corporal perfumado luna confiante2 300 m', 
            `purchase_price` => 45.50, 
            `resale_price` => 65.00, 
            `percentage` => '30', 
            `photo_url` => '102420_1766750820.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `user_id` => null, 
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 102465,
            `name` => 'Óleo desodorante corporal perfumado luna confiante', 
            `description` => 'Óleo desodorante corporal perfumado luna confiante 150 ml', 
            `departament` => 'Óleo desodorante corporal perfumado luna confiante 150 ml', 
            `purchase_price` => 67.38, 
            `resale_price` => 94.90, 
            `percentage` => '30', 
            `photo_url` => '102465_1766750935.jpg',  
            `points` => 8, 
        'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 173010,
            `name` => 'Desodorante hidratante corporal perfumado luna ilumina', 
            `description` => 'Desodorante hidratante corporal perfumado luna ilumina 200 g', 
            `departament` => 'Desodorante hidratante corporal perfumado luna ilumina 200 g', 
            `purchase_price` => 90.93, 
            `resale_price` => 129.90, 
            `percentage` => '30', 
            `photo_url` => '173010_1766759035.jpg',  
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 122474,
            `name` => 'Deo parfum luna ilumina feminino', 
            `description` => 'Deo parfum luna ilumina feminino5 50 ml', 
            `departament` => 'Deo parfum luna ilumina feminino5 50 ml', 
            `purchase_price` => 146.23, 
            `resale_price` => 208.90, 
            `percentage` => '30', 
            `photo_url` => '122474_1766759157.jpg',  
            `points` => 19, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 173009,
            `name` => 'Desodorante hidratante corporal perfumado luna intensa', 
            `description` => 'Desodorante hidratante corporal perfumado luna intensa6 200 g', 
            `departament` => 'Desodorante hidratante corporal perfumado luna intensa6 200 g', 
            `purchase_price` => 90.93, 
            `resale_price` => 129.90, 
            `percentage` => '30', 
            `photo_url` => '173009_1766759289.jpg',  
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` =>  173000,
            `name` => 'REFIL Desodorante hidratante corporal perfumado luna ilumina', 
            `description` => 'REFIL Desodorante hidratante corporal perfumado luna ilumina 200 g', 
            `departament` => 'REFIL Desodorante hidratante corporal perfumado luna ilumina 200 g', 
            `purchase_price` => 67.13, 
            `resale_price` => 95.90, 
            `percentage` => '30', 
            `photo_url` => '173000_1766759461.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` =>  173014,
            `name` => 'REFIL Desodorante hidratante corporal perfumado luna intensa', 
            `description` => 'REFIL Desodorante hidratante corporal perfumado luna intensa6 200 g', 
            `departament` => 'REFIL Desodorante hidratante corporal perfumado luna intensa6 200 g', 
            `purchase_price` => 68.09, 
            `resale_price` => 95.90, 
            `percentage` => '30', 
            `photo_url` => '173014_1766759821.jpg',   
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 86935,
            `name` => 'Deo parfum luna intensa feminino', 
            `description` => 'Deo parfum luna intensa feminino6 50 ml', 
            `departament` => 'Deo parfum luna intensa feminino6 50 ml', 
            `purchase_price` => 146.23, 
            `resale_price` => 208.90, 
            `percentage` => '30', 
            `photo_url` => '86935_1766759964.jpg',  
            `points` => 19, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 197460,
            `name` => 'Óleo perfumado corporal 200 ml', 
            `description` => 'Óleo perfumado corporal', 
            `departament` => 'Óleo perfumado corporal 200 ml', 
            `purchase_price` => 90.93, 
            `resale_price` => 129.90, 
            `percentage` => '30', 
            `photo_url` => '197460_1766764725.jpg',  
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 184481,
            `name` => 'Creme perfumado de mãos 40 g', 
            `description` => 'Creme perfumado de mãos 40 g', 
            `departament` => 'Creme perfumado de mãos 40 g', 
            `purchase_price` => 103.53, 
            `resale_price` => 147.90, 
            `percentage` => '30', 
            `photo_url` => '184481_1766764965.jpg',  
            `points` => 4, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 2, 
            `code` => 184829,
            `name` => 'Sabonetes perfumados em barra', 
            `description` => 'Sabonetes perfumados em barra • Caixa com 2 unidades de 90 g cada.', 
            `departament` => 'Sabonetes perfumados em barra • Caixa com 2 unidades de 90 g cada.', 
            `purchase_price` => 35.43, 
            `resale_price` => 49.90, 
            `percentage` => '30', 
            `photo_url` => '184829_1766767474.jpg',  
            `points` => 4, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 178907,
            `name` => 'Eau de parfum aura alba 75 ml', 
            `description` => 'Eau de parfum aura alba 75 ml', 
            `departament` => 'Eau de parfum aura alba 75 ml', 
            `purchase_price` => 226.80, 
            `resale_price` => 324.00, 
            `percentage` => '30', 
            `photo_url` => '178907_1766768760.jpg',  
            `points` => 29, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 54522,
            `name` => 'Deo parfum ilía feminino 50 ml', 
            `description` => 'Deo parfum ilía feminino 50 ml', 
            `departament` => 'Deo parfum ilía feminino 50 ml', 
            `purchase_price` => 138.38, 
            `resale_price` => 194.90, 
            `percentage` => '30', 
            `photo_url` => '54522_1766777334.jpg',  
            `points` => 17, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 83314,
            `name` => 'Deo parfum ilía secreto feminino 50 ml', 
            `description` => 'Deo parfum ilía secreto feminino 50 ml', 
            `departament` => 'Deo parfum ilía secreto feminino 50 ml', 
            `purchase_price` => 138.38, 
            `resale_price` => 194.90, 
            `percentage` => '30', 
            `photo_url` => '83314_1766777467.jpg',  
            `points` => 17, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 102419,
            `name` => 'Deo parfum ilía ser feminino1 50 ml', 
            `description` => 'Deo parfum ilía ser feminino1 50 ml', 
            `departament` => 'Deo parfum ilía ser feminino1 50 ml', 
            `purchase_price` => 136.43, 
            `resale_price` => 194.90, 
            `percentage` => '30', 
            `photo_url` => '102419_1766777700.jpg',  
            `points` => 16, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 122470,
            `name` => 'Deo parfum ilía completa feminino2 50 ml', 
            `departament` => 'Deo parfum ilía completa feminino2 50 ml', 'Deo parfum ilía completa feminino2 50 ml', 
            `purchase_price` => 136.43, 
            `resale_price` => 194.90, 
            `percentage` => '30', 
            `photo_url` => '122470_1766777993.jpg',  
            `points` => 17, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 148477,
            `name` => 'Eau de parfum ekos pedra 50 ml', 
            `description` => 'Eau de parfum ekos pedra 50 ml', 
            `departament` => 'Eau de parfum ekos pedra 50 ml', 
            `purchase_price` => 266.24, 
            `resale_price` => 374.99, 
            `percentage` => '30', 
            `photo_url` => '148477_1766778747.jpg',  
            `points` => 34, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            'supplier_id' => 1, 
            'category_id' => 1, 
            'code' => 148478,
            `name' => 'Eau de parfum ekos raiz 50 m', 
            'description' => 'Eau de parfum ekos raiz 50 m', 
            'departament` => 'Eau de parfum ekos raiz 50 m', 
            'purchase_price' => 262.50, 
            `resale_price` => 375.00, 
            `percentage` => '30', 
            `photo_url` => '148478_1766778873.jpg',  
            `points` => 34, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 148479,
            `name` => 'Eau de parfum ekos alma 50 ml', 
            `description` => 'Eau de parfum ekos alma 50 ml', 
            `departament` => 'Eau de parfum ekos alma 50 ml', 
            `purchase_price` => 262.50, 
            `resale_price` => 375.00, 
            `percentage` => '30', 
            `photo_url` => '148479_1766779301.jpg',  
            `points` => 34,
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 193490,
            `name` => 'Desodorante colônia ekos ryo floresta 75 ml', 
            `description` => 'Desodorante colônia ekos ryo floresta 75 ml', 
            `departament` => 'Desodorante colônia ekos ryo floresta 75 ml', 
            `purchase_price` => 132.93, 
            `resale_price` => 189.90, 
            `percentage` => '30', 
            `photo_url` => '193490_1766779835.jpg',  
            `points` => 17, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);

        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 189863,
            `name` => 'Sabonete em barra puro vegetal cremoso ekos ryos sortido', 
            `description` => '• Caixa com 3 unidades (1 ryo festa, 1 ryo chuva e 1 ryo vivo) de 150 g cada.', 
            `departament` =>  'Sabonete em barra puro vegetal cremoso ekos ryos sortido', 
            `purchase_price` => 53.83, 
            `resale_price` => 76.90, 
            `percentage` => '30', 
            `photo_url` => '189863_1766780461.jpg',  
            `points` => 5, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 192150,
            `name` => 'Óleo trifásico desodorante corporal ekos ryo floresta 200 ml', 
            `description` => 'Óleo trifásico desodorante corporal ekos ryo floresta 200 ml', 
            `departament` => 'Óleo trifásico desodorante corporal ekos ryo floresta 200 ml', 
            `purchase_price` => 67.83, 
            `resale_price` => 96.90, 
            `percentage` => '30', 
            `photo_url` => '192150_1766780621.jpg',  
            `points` => 8, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 133863,
            `name` => 'Desodorante colônia ekos ryo chuva 75 ml', 
            `description` => '• Cítrico aquoso moderado. • Fragrância viva e intensa.', 
            `departament` => 'Desodorante colônia ekos ryo chuva 75 ml', 
            `purchase_price` => 132.93, 
            `resale_price` => 189.90, 
            `percentage` => '30', 
            `photo_url` => '133863_1766780826.jpg',  
            `points` => 17, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 1, 
            `code` => 150192,
            `name` => 'Desodorante colônia ekos ryo festa 75 ml', 
            `description` => 'Desodorante colônia ekos ryo festa 75 ml • Amadeirado aquoso moderado. • Fragrância p', 
            `departament` => 'Desodorante colônia ekos ryo festa 75 ml', 
            `purchase_price` => 132.93, 
            `resale_price` => 189.90, 
            `percentage` => '30', 
            `photo_url` => '150192_1766780980.jpg',  
            `points` => 17, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([ 
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 133865,
            `name` => 'Desodorante colônia ekos ryo vivo 75 ml', 
            `description` => 'Desodorante colônia ekos ryo vivo 75 ml • Floral aquoso. • Fragrância afetiva e profunda.', 
            `departament` => 'Desodorante colônia ekos ryo vivo 75 ml', 
            `purchase_price` => 132.93, 
            `resale_price` => 189.90, 
            `percentage` => '30', 
            `photo_url` => '133865_1766781154.jpg',  
            `points` => -117, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
            
        DB::table('products')->insert([
            `supplier_id` => 1, 
            `category_id` => 3, 
            `code` => 132672,
            `name` => 'Desodorante colônia frescor maracujá natureza dos', 
            `description` => 'Desodorante colônia frescor maracujá natureza dos sonhos feminino 150 ml', 
            `departament` => 'Desodorante colônia frescor maracujá natureza dos sonhos feminino 150 ml', 
            `purchase_price` => 87.43, 
            `resale_price` => 124.90, 
            `percentage` => '30', 
            `photo_url` => '132672_1766781846.jpg',  
            `points` => 11, 
            'created_at' => now(),
            'updated_at' => now(),
            ]);
    }
}